theme: jekyll-theme-dinky
title: Débuter en finance décentralisée DeFi et en blockchain
description: Cette page répertorie les liens qui ont été échangés sur le groupe télégram DeFi Francophone et à pour but de guider les nouveaux venus dans l'univers de la DeFi.
